<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_GET OTP_exchange2</name>
   <tag></tag>
   <elementGuidId>c2e27fc8-69e1-430d-92fe-a544a72edfc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='exchange2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#exchange2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>6146aa00-f3c0-4412-9def-fa359501860b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exchange2</value>
      <webElementGuid>8bebd2ca-4353-4ff8-b099-bc2f34859e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>canvas__anim_width-160</value>
      <webElementGuid>5df32460-c74f-4a49-b7cf-13d61974f28a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>307</value>
      <webElementGuid>cde19383-b402-4d27-b875-1c3e61510d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>153</value>
      <webElementGuid>15bca107-a89a-4dc2-b9cc-6fc2b49ffc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exchange2&quot;)</value>
      <webElementGuid>3287d045-65d2-4ac5-8933-dfd8a6e9dcac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='exchange2']</value>
      <webElementGuid>4adbaf7c-afda-45ce-83d0-47afef613138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div/ui-view/div/div/div/div/div/div/div[3]/div[2]/div[2]/canvas</value>
      <webElementGuid>173b8342-e0a4-42d7-be6d-25f9cc395a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/canvas</value>
      <webElementGuid>f5d396e8-24ce-405c-9f22-cce8f4a3f89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'exchange2']</value>
      <webElementGuid>aa80e8c4-c94c-4598-9d64-551e63d54f67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
