<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_GET OTP_exchange1</name>
   <tag></tag>
   <elementGuidId>baa48f56-fb8c-4de5-a2f8-d1f6887944d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='exchange1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#exchange1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>d8a6f914-cc6d-4785-90a9-3e726e657a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exchange1</value>
      <webElementGuid>ce953657-d4f1-45f6-8b3c-5f03bedf047f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>canvas__anim_width-141</value>
      <webElementGuid>f7073a90-dc53-43e2-b26b-54e5dfd6046a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>282</value>
      <webElementGuid>a943bdc6-c8a2-427b-8bc6-1c9a44adda98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>141</value>
      <webElementGuid>ae11088b-c6b4-4a64-be78-110648735c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exchange1&quot;)</value>
      <webElementGuid>3aca41a5-9053-41db-b2d4-d2493d88df44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='exchange1']</value>
      <webElementGuid>bbe52747-b29d-41d7-825d-e79efb9420c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div/ui-view/div/div/div/div/div/div/div[3]/div[2]/div/canvas</value>
      <webElementGuid>64489c00-9abc-4557-8669-8a332a40fa59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>f5efb1a5-d185-450e-b9fb-c29611861c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'exchange1']</value>
      <webElementGuid>cbf9e8bf-7351-41e6-a62f-a312873bc14c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
