<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gent_odds</name>
   <tag></tag>
   <elementGuidId>2f8e8cd2-fb04-4e2a-beb2-2f4e5c11af43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='odds']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;odds&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e65b0cd2-3017-42cc-b8ff-bd00dfee7a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>588e407e-b5f6-4a0d-87e3-40209136316d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>cf32eccf-6cf8-4b69-8d7d-00671b4d83c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>betslip-price-ladder__input ng-pristine ng-valid ng-not-empty ng-valid-maxlength ng-touched</value>
      <webElementGuid>c89976dd-93d3-4143-86e1-d412312e4cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>odds</value>
      <webElementGuid>f4521c58-3ad4-4675-a45f-a8f879443249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>49f3b6ee-23c6-4bee-9c75-c68c732568cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1.9</value>
      <webElementGuid>6d64c4f0-ef39-4efc-9feb-d720ed736da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>9501f2b9-5198-4a2c-865c-ca9a7447e2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;placeBet_&quot;)/betslip-potential-bet[1]/section[@class=&quot;betslip__potential-bet--back&quot;]/betslip-editable-bet[1]/section[@class=&quot;betslip__editable-bet&quot;]/div[@class=&quot;betslip__editable-bet__container&quot;]/div[@class=&quot;betslip__editable-bet__item betslip__editable-bet__cell&quot;]/betslip-price-ladder[1]/div[@class=&quot;betslip-price-ladder&quot;]/input[@class=&quot;betslip-price-ladder__input ng-pristine ng-valid ng-not-empty ng-valid-maxlength ng-touched&quot;]</value>
      <webElementGuid>5843b423-a5d9-4dc7-9b45-e3beb0b5859e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='odds']</value>
      <webElementGuid>db4ef4d1-d78d-4f7b-896e-84d706617399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='placeBet_']/betslip-potential-bet/section/betslip-editable-bet/section/div[2]/div/betslip-price-ladder/div/input</value>
      <webElementGuid>7106856c-b11e-440a-ad9b-69559e387504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//betslip-price-ladder/div/input</value>
      <webElementGuid>38394b12-2c03-474a-b40a-62e056bb344b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'odds']</value>
      <webElementGuid>0ca5a271-1cbe-4672-8e6b-df35d23ba989</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
