<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1.9</name>
   <tag></tag>
   <elementGuidId>d1dbd55e-a623-4c5c-b4cc-58a80aac0b61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//bf-main-market[@id='main_market']/bf-main-marketview/div/div[2]/bf-marketview-runners-list[2]/div/div/div/table/tbody/tr/td[4]/button/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.0_back.back.mv-bet-button.ng-isolate-scope.back-button.back-selection-button > div.mv-bet-button-info.ng-scope > span.bet-button-price.price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c4f9de40-48d1-4ce8-8b28-b183ff9e358d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bet-button-price price</value>
      <webElementGuid>3f17f805-4d8c-41ba-b7f4-836dcef07505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1.9</value>
      <webElementGuid>1d753df8-353d-4daa-ad97-5faf8c286a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_market&quot;)/bf-main-marketview[@class=&quot;ng-scope ng-isolate-scope market_container main_market cls_marketdetails&quot;]/div[@class=&quot;mv-sticky-container scroll-to-current-element id33423&quot;]/div[@class=&quot;main-mv-runners-list-wrapper&quot;]/bf-marketview-runners-list[@class=&quot;runners-list-unpinned ng-isolate-scope&quot;]/div[@class=&quot;marketview-list-runners-component bf-row&quot;]/div[@class=&quot;runners-container bf-col-24-24&quot;]/div[@class=&quot;mv-runner-list-container overlayPosition&quot;]/table[@class=&quot;mv-runner-list datalist&quot;]/tbody[1]/tr[@class=&quot;runner-line ng-scope&quot;]/td[@class=&quot;bet-buttons back-cell ng-scope last-back-cell 350594&quot;]/button[@class=&quot;0_back back mv-bet-button ng-isolate-scope back-button back-selection-button&quot;]/div[@class=&quot;mv-bet-button-info ng-scope&quot;]/span[@class=&quot;bet-button-price price&quot;]</value>
      <webElementGuid>7fb7b811-02fb-4e13-ba99-2b97d6d1a51b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//bf-main-market[@id='main_market']/bf-main-marketview/div/div[2]/bf-marketview-runners-list[2]/div/div/div/table/tbody/tr/td[4]/button/div/span</value>
      <webElementGuid>010fc1be-4763-4b9f-978c-a7b870616e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹1243'])[1]/following::span[1]</value>
      <webElementGuid>1d034c42-eb3f-478f-8382-37796ca4b294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹2093'])[1]/following::span[3]</value>
      <webElementGuid>a62aabb1-40f0-485f-9782-513733abf0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹3941'])[1]/preceding::span[1]</value>
      <webElementGuid>b2b4b75d-59d7-48b9-9411-22dce4b649b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹1402'])[1]/preceding::span[3]</value>
      <webElementGuid>fe021792-5a60-426f-84a2-64c768e588da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1.9']/parent::*</value>
      <webElementGuid>a693d9da-feb4-4059-8ed6-fc08db127206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/button/div/span</value>
      <webElementGuid>83957d93-b447-475a-8da8-ccfbd6893ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1.9' or . = '1.9')]</value>
      <webElementGuid>51749192-24e0-4ab3-bb72-b7fa6fb534a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
