<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Badminton</name>
   <tag></tag>
   <elementGuidId>3e03a341-4df7-4612-b8c4-c50c59487bc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mod-sportshighlights-new-1015']/div[2]/ul/li[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5685421e-6b1e-4472-81d8-90f8ea7eeb56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-nav sports-tab ui-clickselect</value>
      <webElementGuid>c2c977cf-f016-46df-adca-5a48ab2b41cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Badminton</value>
      <webElementGuid>248d434e-14e0-4948-bcb0-70e928365809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sportname</name>
      <type>Main</type>
      <value>Badminton</value>
      <webElementGuid>3f2b9561-850c-4f92-84f3-02a11b5e9311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sport_url</name>
      <type>Main</type>
      <value>srsport31</value>
      <webElementGuid>6901c2b7-2915-4e27-8fd5-40376f719bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                 
                                   Badminton 
                                 </value>
      <webElementGuid>7f9f6ea9-0723-455c-be0a-14d3bd7644df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mod-sportshighlights-new-1015&quot;)/div[@class=&quot;sports-list list-5 cl_sports_list ksr____sec__301&quot;]/ul[@class=&quot;ui-clickselect-container allSportFilterOneContainer&quot;]/li[@class=&quot;sports-item ui-gtm-click sportFilterOne cl_line_links&quot;]/a[@class=&quot;ui-nav sports-tab ui-clickselect&quot;]</value>
      <webElementGuid>abd3f49e-f036-4511-bef8-16b7bacdbaf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mod-sportshighlights-new-1015']/div[2]/ul/li[6]/a</value>
      <webElementGuid>6cda17e0-6626-4a68-857c-a64b0fbd1035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(43)'])[1]/following::a[1]</value>
      <webElementGuid>ff0a386b-6565-471d-a950-4c112548a051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/ul/li[6]/a</value>
      <webElementGuid>7164240c-55a2-45b4-b3d5-dbbb994fb16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Badminton' and (text() = '
                                 
                                   Badminton 
                                 ' or . = '
                                 
                                   Badminton 
                                 ')]</value>
      <webElementGuid>cfc8255d-975f-4d3f-93eb-966246831423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
