<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sportsbook</name>
   <tag></tag>
   <elementGuidId>7bddf192-6409-4972-84dc-fe6d7c32c78e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='SPORTSBOOK']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SPORTSBOOK</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2c597377-e92f-423f-a99b-fbf16363ab70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SPORTSBOOK</value>
      <webElementGuid>3993af0e-75d0-493d-8199-4bf2b503f3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://haboom.com/sportsbook/highlight</value>
      <webElementGuid>4b657799-eca1-45e0-b5fa-c644de5d6cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>bbddacbe-f1b7-4ae5-8748-2d60ae799062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sportsbook</value>
      <webElementGuid>1bbb2669-0c31-4eca-a16c-7ff3cad58650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtml</name>
      <type>Main</type>
      <value>SPORTSBOOK</value>
      <webElementGuid>250fae06-6f28-45d2-acc1-34efe83340de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            Sportsbook </value>
      <webElementGuid>325d0c51-6a4a-4c32-b1c6-4c28fc36c882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SPORTSBOOK&quot;)</value>
      <webElementGuid>ee071ddc-7dc8-4e16-9c31-12055fa25e5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='SPORTSBOOK']</value>
      <webElementGuid>6e13aaa7-42da-473c-920a-9eec4ed5b6e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ssc-pn']/li[3]/a</value>
      <webElementGuid>e70e9484-142f-404c-ba85-36be4cbb2e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sportsbook')]</value>
      <webElementGuid>99bdc7e0-b5af-434f-921f-d0a62827f3ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exchange'])[1]/following::a[1]</value>
      <webElementGuid>361263c8-8324-425e-b872-6f7e5f873ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>86546c27-31e7-4cf3-ae25-8170e2900f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casino'])[1]/preceding::a[1]</value>
      <webElementGuid>afaf0483-35b5-4b0c-b338-9d7609c3aab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casino'])[2]/preceding::a[2]</value>
      <webElementGuid>b916d9d9-7155-43aa-a849-d1dda8aa36b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sportsbook']/parent::*</value>
      <webElementGuid>b61178c2-f235-47f9-aeb9-3616b9c0c71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://haboom.com/sportsbook/highlight')]</value>
      <webElementGuid>998a9533-f817-4064-a350-63d31fc08ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[3]/a</value>
      <webElementGuid>44e5d253-d9b7-4495-8cd6-7f79de2340d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'SPORTSBOOK' and @href = 'https://haboom.com/sportsbook/highlight' and @title = 'Sportsbook' and (text() = '
                                                            Sportsbook ' or . = '
                                                            Sportsbook ')]</value>
      <webElementGuid>03416666-352c-4201-9104-3599dfcb7a34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
