<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EZUGI_provider_list</name>
   <tag></tag>
   <elementGuidId>679c6c64-2ecf-4db9-b8e2-74904b748faf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='provider_list'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > label > input[name=&quot;provider_list&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65346508-50bf-4e99-be4a-0e7dd308561c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-custom</value>
      <webElementGuid>efdb0c78-6109-4817-a35d-e9c77b605041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>ezugi</value>
      <webElementGuid>e5c17a87-beb6-444d-8d3a-55a956d8ebf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-table</name>
      <type>Main</type>
      <value>cg</value>
      <webElementGuid>76693365-b6b7-44b3-a815-ea378682e7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9d67b64d-e75e-464e-83a3-541e45072ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>provider_list</value>
      <webElementGuid>97aa2c79-f747-489d-b0bf-14c3022c5002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main desktop&quot;]/div[4]/div[@class=&quot;container wrapper cls-scroll-wrapper&quot;]/ul[@class=&quot;form-group slots_filter cls_listing&quot;]/li[2]/label[1]/input[@class=&quot;radio-custom&quot;]</value>
      <webElementGuid>4deb7f08-9a56-4949-82e6-f0958a1c49f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='provider_list'])[2]</value>
      <webElementGuid>6361ecc4-0f76-47a6-8ac4-0b295984eca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div[2]/ul/li[2]/label/input</value>
      <webElementGuid>1ef003e0-dffd-4bc1-af76-c29af52d09da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/label/input</value>
      <webElementGuid>7258bcde-0322-4f4c-8886-5a4270b87c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'provider_list']</value>
      <webElementGuid>63b30874-bc6d-4d50-bef1-e816abf03605</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
