<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Casino</name>
   <tag></tag>
   <elementGuidId>332d5cc1-e676-48ce-9b7b-1065b31a4162</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='GAMING']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GAMING</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f586eed-3be4-4faa-8cd8-1f6f5aee1f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GAMING</value>
      <webElementGuid>9612790b-dc2c-4210-848f-7a0ff423bc5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://haboom.com/d/casino/casino</value>
      <webElementGuid>6e433c0e-824f-4d92-8063-a154758f6097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>604e26e9-c870-4112-a895-0152265c3e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Casino</value>
      <webElementGuid>d96ae612-142a-4d9f-99db-c637745e4df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtml</name>
      <type>Main</type>
      <value>GAMING</value>
      <webElementGuid>8a912b23-3d64-4335-bc9e-514070a238dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                               Casino
                                                            </value>
      <webElementGuid>9a33d1ca-76c0-4f8a-801c-b6375c102e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GAMING&quot;)</value>
      <webElementGuid>16e78de0-04cd-40a0-a278-d8f572900f2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='GAMING']</value>
      <webElementGuid>f042388d-c581-4054-86e4-2c4822810dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ssc-mgr-GAMING']/a</value>
      <webElementGuid>77bcb265-5e11-410e-a82b-ccd746813ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Casino')])[2]</value>
      <webElementGuid>9aaa1e6a-fe61-488f-862c-9a9701bc0d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casino'])[1]/following::a[1]</value>
      <webElementGuid>03463de8-23c4-4b9d-af82-6f808fa94453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sportsbook'])[1]/following::a[2]</value>
      <webElementGuid>ebfa7703-6c04-4c2e-9ac6-095f39049923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slots'])[1]/preceding::a[1]</value>
      <webElementGuid>924069b6-f382-4165-bc08-2d2516e0c67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live Casino'])[1]/preceding::a[2]</value>
      <webElementGuid>2b51d1ce-96bf-49e8-9c91-cb766c145da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://haboom.com/d/casino/casino')])[2]</value>
      <webElementGuid>172d741b-d5e5-40ea-b0e2-f38db45de682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>0624c3e6-92a9-445d-b023-5dfb90dcd39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'GAMING' and @href = 'https://haboom.com/d/casino/casino' and @title = 'Casino' and (text() = '
                                                               Casino
                                                            ' or . = '
                                                               Casino
                                                            ')]</value>
      <webElementGuid>0d435f87-7ce6-48b0-a425-cc0eeb1a8e71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
