<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EZUGI_provider_list</name>
   <tag></tag>
   <elementGuidId>db76f236-933e-4c6a-9fea-c3cf2a73ec6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='provider_list'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > label > input[name=&quot;provider_list&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>141da652-36a1-4f8c-a57b-8d08a74b4820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-custom</value>
      <webElementGuid>25746b91-81cc-470f-ba75-b33a88ae876e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>ezugi</value>
      <webElementGuid>47ce3e8c-2f19-4ddf-8d01-bc1419ad6018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-table</name>
      <type>Main</type>
      <value>cg</value>
      <webElementGuid>b87d0b5e-9f8c-4bfb-9426-0c363485a069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>da2d38e7-02b1-49fa-b58e-1f45350fb60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>provider_list</value>
      <webElementGuid>e3c737b1-013c-431f-bdc3-07615b966b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main desktop&quot;]/div[4]/div[@class=&quot;container wrapper cls-scroll-wrapper&quot;]/ul[@class=&quot;form-group slots_filter cls_listing&quot;]/li[2]/label[1]/input[@class=&quot;radio-custom&quot;]</value>
      <webElementGuid>16b4ff5a-7d86-4d0b-97e0-70c2d0e8166b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='provider_list'])[2]</value>
      <webElementGuid>0b009443-4215-421a-ac93-cd134e3639ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div[2]/ul/li[2]/label/input</value>
      <webElementGuid>5e0d4b55-20e7-4f0f-83b9-f61e2aa5560a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/label/input</value>
      <webElementGuid>c822705b-63ed-4161-a41d-fadd484bca46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'provider_list']</value>
      <webElementGuid>ece8991f-3b2b-45ca-b7fb-8baf4cdccbef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
